export const GETCITIES = 'GET_CITIES'
export const GETCITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GETCITIES_FAILURE = 'GET_CITIES_FAILURE'

export const GET_CITIES_BY_SEARCHVALUE = 'GET_CITIES_BY_SEARCHVALUE'
export const GET_CITIES_BY_SEARCHVALUE_SUCCESS = 'GET_CITIES_BY_SEARCHVALUE_SUCCESS'
export const GET_CITIES_BY_SEARCHVALUE_FAIL = 'GET_CITIES_BY_SEARCHVALUE_FAIL'
